WOQL.and(
	WOQL.doctype("GitHubRepository")
        .label("Git Hub Repository")
        .description("A GitHub repository of interest")
		.property("gitHub_repository_html_url", "xdd:url")
		    .label("GitHub Repository Url")
		.property("gitHub_repository_star", "scm:GitHubStar")
			.label("GitHub Repository Star"),
    WOQL.doctype("GitHubUser")
		.label("Git Hub User")
		.description("A GitHub User")
		.property("gitHub_user_html_url", "xdd:url")
            .label("GitHub User Url")
		.property("gitHub_user_email", "email")
            .label("GitHub User Email")
		.property("gitHub_user_avatar", "xdd:url")
            .label("GitHub User Avatar")
		.property("gitHub_user_star", "scm:GitHubStar")
			.label("GitHub User Star"),
    WOQL.add_class("GitHubStar")
        .label("GitHub Star")
		.property("starred_at", "dateTime")
			.label("Starred at")
		.property("unstarred_at", "dateTime")
			.label("Unstarred at")
		.property("action", "string")
			.label("Action")
)
